email: address@nih.gov
## directory where we clone this repo locally
scriptdir: /path/to/virome-pipeline
clusterfile: /path/to/virome-pipeline/vp.locus.yaml

## directories
workdir: /path/to/workingdir
# these directories are relative to the working directory - use full path if the dir is somewhere else
indir: input
outdir: virome_output

## rule specific parameters that could change between projects
## we will use default db
## checkvdb: /hpcdata/bio_data/checkv/checkv-db-v1.0

## input files
# input files are expected to be like {indir}/{sampleprefix}{assembly_suffix}
assembly_suffix: .scaffolds.fasta

# sample prefixes to be used throughout pipeline
samples:
  S105b
  S105c
