__default__:
    threads: 16
    h_vmem: 2G
    extra: ''
    tmpdir: "$TMP"
    log: '{wildcards.sample}/logs'
    jobname: '{wildcards.sample}'


vs1:
  modules: virsorter/2.2.3-Python-3.8.10

checkv:
  h_vmem: 1G
  modules:
    - checkv/0.8.1
    - Python/2.7.15-foss-2018b

vs4dramv:
  modules: virsorter/2.2.3-Python-3.8.10

dramv:
  h_vmem: 3G
  modules:
    - /hpcdata/bcbb/shared/microbiome_share/modules/dram/1.4.6_ms

diamond:
  threads: 8
  h_vmem: 12G
  modules: diamond/2.0.15.153
  tmpdir: /tmp
  ## on Locus /tmp is on local disk but $TMPDIR is not and for diamond this matters
