__default__:
    threads: 16
    h_vmem: 2G
    extra: ''
    tmpdir: "$TMP"
    log: '{wildcards.sample}/logs'
    jobname: '{wildcards.sample}'


genomad:
  modules: genomad/1.5.2

verse:
  threads: 8
  modules:
    - verse/0.1.5
    - Python/3.7.3

checkv:
  h_vmem: 1G
  modules:
    - checkv/0.8.1
    - Python/2.7.15-foss-2018b

bbmap:
  h_vmem: 8G
  modules: bbmap/38.90
  log: 'bbmap_log'
  jobname: 'all'

mmseqs: 
  h_vmem: 15G
  modules: mmseqs2/14.7e284
  log: 'mmseqs_log'
  jobname: 'all'

dramv:
  h_vmem: 3G
  modules:
    - /hpcdata/bcbb/shared/microbiome_share/modules/dram/1.4.6_ms

iphop:
  h_vmem: 15G
  modules:
    - iphop/1.3.0

diamond:
  threads: 8
  h_vmem: 12G
  modules: diamond/2.0.15.153
  tmpdir: /tmp
  ## on Locus /tmp is on local disk but $TMPDIR is not and for diamond this matters
