email: address@nih.gov
## directory where we clone this repo locally
scriptdir: /path/to/virome-pipeline
clusterfile: /path/to/virome-pipeline/locus.cluster_config.yaml

## directories
workdir: /path/to/workingdir
# these directories are relative to the working directory - use full path if the dir is somewhere else
# they need to exist
indir: input
outdir: virome_output

### rule-specific parameters that could change between projects

#genomad database current location
genomaddb: /hpcdata/bio_data/genomad/genomad_db/

# checkv database
checkvdb: /hpcdata/bio_data/checkv/checkv-db-v1.5

# min contig length for virsorter and dramv
vs_min_length: 1000

#iphop 
iphopdb: /hpcdata/bio_data/iphop/Sept_2021_pub_rw/

# diamond db to annotate genes for eventual pathway inference - we use nr
diamonddb: /hpcdata/bcbb/shared/microbiome_share/dbs/diamond_nr/nr.diamond.dmnd

### input files
# input files are expected to be like {indir}/{sample prefix}{assembly_suffix}
assembly_suffix: .scaffolds.fasta

## genomad output is automatically everything that comes before .fasta, so consider changing assembly suffix to .fasta and including other strings to sample name below - possibly a way around this but haven't figured it out yet. 

# sample prefixes to be used throughout pipeline
samples:
  Sample1
  Sample2
